addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.15.0")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.31")
addSbtPlugin("org.scalameta" %% "sbt-scalafmt" % "2.0.4")
addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.8.3")
addSbtPlugin("org.scalatra.sbt" % "sbt-scalatra" % "1.0.3")
