addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.15.0")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.28")
addSbtPlugin("com.geirsson"  %% "sbt-scalafmt" % "1.6.0-RC3")
addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.8.3")
addSbtPlugin("org.scalatra.sbt" % "sbt-scalatra" % "1.0.1")
